# Generated by Django 6.0.7 on 2026-08-18 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('zh', 'Simplified Chinese')], default='en', max_length=2)),
                ('target_role', models.CharField(default='Untitled Analysis', max_length=255)),
                ('status', models.CharField(choices=[('started', 'Started'), ('analysis_completed', 'Analysis completed'), ('priorities_completed', 'Priorities completed'), ('roadmap_completed', 'Roadmap completed')], default='started', max_length=32)),
                ('analysis_snapshot', models.JSONField(blank=True, default=dict)),
                ('priority_snapshot', models.JSONField(blank=True, default=dict)),
                ('roadmap_snapshot', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
