# Generated by Django 6.0.7 on 2026-08-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrecord',
            name='display_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
